name: CI
on:
  push:
    branches: [z]
  pull_request:
    branches: [main]
jobs:
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: pnpm run test
